baseURL = 'https://gulomer.com/'
languageCode = 'en-us'
title = 'Ömer Melih Gül'
theme = 'paper'

[menus]
[[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 10
[[menu.main]]
    name = 'CV'
    url = 'https://google.com/'
    weight = 20
    [menu.main.params]
        external = true

# disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'omermelihgul'                  # twitter.com/YOUR_TWITTER_ID
  github = 'omermelihgul'                 # github.com/YOUR_GITHUB_ID
  # instagram = 'omermgul'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'omermelihgul'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  # rss = true                                # show rss icon

  # home page profile
  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Ömer Melih Gül'
  bio = 'YOUR_BIO'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://cdn.v2ex.com/gravatar/'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)

  # giscus
# [params.giscus]
#   repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
#   repoId = 'YOUR_GISCUS_REPO_ID'
#   category = 'YOUR__GISCUS_CATEGORY'
#   categoryId = 'YOUR_GISCUS_CATEGORY_ID'
#   mapping = 'pathname'
#   theme = 'light'
#   lang = 'zh-CN'
